#-------------------------------
# Site Settings
title: Hella
description: Hella Consulting - Web3 Native Fractional Engineering, DevRel, Digital Marketing & Strategy
logo: /images/hella-logo-4.png
logo_dark: /images/hella-logo-3.jpg
baseurl:

#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - url: '/services/'
      title: 'Services'
    - url: '/team/'
      title: 'Team'
    - url: '/contact/'
      title: 'Contact'
    - url: '/blog/'
      title: 'Blog'

#-------------------------------
# SEO Settings
site_author: Hella Consulting
twitter_username: Hella_Web3
default_image: /images/hella-logo-4.png
keywords: Web3, Consulting, Engineering, DevRel, Digital Marketing, Strategy, Blockchain


#-------------------------------
# Author Settings
author:
  author_name: Chris Anatalio
  author_avatar: images/chris1.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Hella
  hero_subtitle: Web3-Native Fractional Engineering, DevRel, Digital Marketing & Strategy
  hero_description: |
    Full-service consultancy with broad experience across Web2, Enterprise and Web3
  hero_image: /images/101.jpg
  hero_button_text: Let's Go
  hero_button_link: '/contact/'

# Team
team:
  enable: true
  team_title: Hella Teamwork
  team_link: '/team/'
  team_image:
    - alt: "Chris Anatalio"
      image: "/images/chris1.jpg"
    - alt: "Anna Lopatina"
      image: "/images/anna1.jpg"
    - alt: "Placeholder"
      image: "/images/02.jpg"
    - alt: "Logo"
      image: "/images/hella-logo-1.png"
#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: Topic Zero Blog

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Monthly Up-level ✌️
  mailchimp_description: Actionable tips and alpha for enhancing productivity from an industry veterans.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email...
  mailchimp_button_text: No fluff, Just Value


#-------------------------------
# Footer Settings
footer_description: Unleash your Web3 Idea with Hella

#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://x.com/Hella_Web3"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/hella-web3"}
- { icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/company/hella-web3" }
- { icon: "fa-brands fa-youtube", name: "Youtube", link: "https://www.youtube.com/@hella-web3" }
- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

contact:
  form_id: xwpqrreq
  button_text: Let's go


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: dsq-count-scr
  disqus_title: Start the conversation
  disqus_button_text: Show Comments

google_analytics: G-WCD2Q24SBK